#!/bin/bash
set -e

echo "Setting up your environment..."


if test ! $(which redis-server)
then
  echo "  x You need to install Redis. If you use Homebrew, you can run:"
  echo "    brew install redis"
  exit
fi


if test ! $(which memcached)
then
  echo " x You need to install Memcached:"
  echo "   brew install memcached"
  exit
fi


if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
fi


bundle install

bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake db:seed

foreman start

echo "Done!"
