#!/bin/bash
set -e

echo "Setting up your environment..."


if test ! $(which redis-server)
then
  echo "  x You need to install Redis. If you use Homebrew, you can run:"
  echo "    brew install redis"
  exit
fi


if test ! $(which memcached)
then
  echo " x You need to install Memcached:"
  echo "   brew install memcached"
  exit
fi


if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
fi


bundle install


echo "copying the example files config files..."
cp ./config/application.example.yml ./config/application.yml
cp ./config/database.example.yml ./config/database.yml

echo "please update the config/application.yml with your application client ID and secret"
echo "when finished, you may continue..."
read -p "continue (y/n)?"
  if [ $REPLY != "y" ]; then
    echo "Exiting..."
    exit 1
  fi

echo "the database will now be created, migrated and seeded"
echo "the current default is sqlite, if you'd like to customize your db settings"
echo "update the config/database.yml file"
echo "when finished, you may continue..."
read -p "continue (y/n)?"
  if [ $REPLY != "y" ]; then
    echo "Exiting..."
    exit 1
  fi

echo "starting redis with sidekiq, and memcached in the background..."
foreman start &


echo "creating the database..."
bundle exec rake db:create

echo "migrating the database..."
bundle exec rake db:migrate


echo "Done!"
